apiVersion: v2
name: ghostfolio
description: Unofficial Helm chart for Ghostfolio, an open source wealth management software.
icon: https://avatars.githubusercontent.com/u/82473144
annotations:
  artifacthub.io/alternativeName: ghostfolio-helm
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/J4NS-R/ghostfolio-helm
    - name: Ghostfolio source
      url: https://github.com/ghostfolio/ghostfolio
  artifacthub.io/maintainers: |
    - name: Jans Rautenbach
      email: git@moat.rauten.co.za

dependencies:
  - name: postgres
    version: "0.18.3"
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: postgres.enabled
  - name: valkey
    version: "0.9.3"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.enabled

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# https://github.com/ghostfolio/ghostfolio/releases
appVersion: "2.250.0"
