apiVersion: v2
name: ghostfolio
description: Unofficial Helm chart for Ghostfolio, an open source wealth management software.
icon: https://nobsdelivr.private.coffee/gh/selfhst/icons@main/svg/ghostfolio.svg
annotations:
  artifacthub.io/alternativeName: ghostfolio-helm
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/J4NS-R/ghostfolio-helm
    - name: Ghostfolio source
      url: https://github.com/ghostfolio/ghostfolio
  artifacthub.io/maintainers: |
    - name: J4NS-R
      email: git@moat.rauten.co.za
  # supported kinds are added, changed, deprecated, removed, fixed and security
  artifacthub.io/changes: |
    - kind: added
      description: Bump postgres subchart to v0.19.0
maintainers:
  - name: J4NS-R
    email: git@moat.rauten.co.za

dependencies:
  - name: postgres
    version: "0.19.0"
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: postgres.enabled
  - name: valkey
    version: "0.9.3"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.enabled

type: application

# Versions follow Semantic Versioning (https://semver.org/)
version: 0.1.6

# https://github.com/ghostfolio/ghostfolio/releases
appVersion: "2.253.0"
