{{- $existingSecret := .Values.ghostfolio.existingSecret | required ".Values.ghostfolio.existingSecret is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghostfolio.fullname" . }}
  labels:
    {{- include "ghostfolio.labels" . | nindent 4 }}
stringData:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "ghostfolio.databaseUrl" . | quote }}
  {{- else }}
  DATABASE_URL: {{ include "ghostfolio.externalDatabaseUrl" . | quote }}
  {{- end }}
