name: Chart CI

on:
  push:
    branches: [master]
    paths:
      - "chart/**"
      - ".github/workflows/helm-unittest.yaml"
  pull_request:
    branches: [master]
    paths:
      - "chart/**"
      - ".github/workflows/helm-unittest.yaml"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm unittest
        uses: d3adb5/helm-unittest-action@v2.5.0
        with:
          charts: chart

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup helm repos
        run: helm repo add valkey https://valkey.io/valkey-helm/

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Lint chart
        run: ct lint --target-branch master --charts chart
